# Generated by Django 3.2.8 on 2021-11-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='tag',
        ),
    ]
